/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:37b9d485-35c5-4b40-88aa-69630db6ec00",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_ClW6loYYP",
    "aws_user_pools_web_client_id": "3c1umvnq91sa0rh6k11g8lvmms",
    "oauth": {}
};


export default awsmobile;
